### ISSUE TITLE
bug: cant change/save timestamp server

### ISSUE THREAD

**Issue by si458** [michaelmsonne/SignToolGUI#11]
# Bug Report

**Version:** v2.0.0.0

**Current behavior:**
1. in the app itself you cant change the timestamp server, its disabled?

2. so you go into menu -> manage timestamp servers, then move certum up to top of the list and click ok, get error
<img width="1024" height="1366" alt="Image" src="https://github.com/user-attachments/assets/64c5c9e1-6678-4ba0-893b-e550de228f6c" />

**Expected behavior:**
1. to be able to change the timestamp server in the main app without changing the position of the server
2. also when saving timestamp servers, for it to not show this error?

**Steps to reproduce:**
see current behavior

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by michaelmsonne** [comment]
Thanks for this report @si458 - good catch! I will dig into it, and update you when I have more info! 👍

**Comment by si458** [comment]
amazingly loads of different errors depending on what i did etc

```
21-10-2025 12:43:23 - [EventID 3012] Error		Error loading timestamp configuration: Could not load file or assembly 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

21-10-2025 12:52:58 - [EventID 3019] Error		Error saving timestamp configuration to file: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

21-10-2025 12:53:02 - [EventID 3017] Error		Error applying timestamp server changes: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

21-10-2025 13:38:29 - [EventID 3009] Error		Error saving timestamp configuration: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by michaelmsonne** [comment]
https://github.com/michaelmsonne/SignToolGUI/releases/download/2.0.0.0/SignToolGUI.v.2.0.0.0.installer.msi should be fixed now :)

**Comment by si458** [comment]
brilliant! 
saves the timestamps now and the orders too!
still cant switch the provider in the main app page and i have to drag Certum to the top of the list in the management bit
but at least it saves it and every time i open it, it uses them for the timestamp!

**Comment by michaelmsonne** [comment]
Nice to hear it works now - the UI in the main UI for timestamp server will be changed when I got the time for it, as is some legacy part in the UI before the management of timestamp servers.
